@startuml as is

skinparam componentStyle uml2
actor Admin
actor User
database AuthDatabase
database BillingDatabase
component Yookassa
component Auth
component AdminPanel
component Billing
component WorkerSubscription
component Notification


User -down-> Auth
Auth -right-> AuthDatabase
Auth -up-> Notification
User -right-> Billing
Billing -right-> BillingDatabase
Billing <-up-> Yookassa
Billing <-up-> Yookassa : статус после оплаты
Billing -down-> Notification
BillingDatabase <--> WorkerSubscription : Воркер добавляет/удаляет(покупка/возврат) роли в Auth модуле
WorkerSubscription -down-> Auth : Он же мониторит окончение подписок(Auth отзывает JWT)
WorkerSubscription -left-> Notification
Admin -left-> AdminPanel
AdminPanel -left-> BillingDatabase

@enduml