version: "3.2"
services:
  billing:
    build: 
      context: ./billing
      dockerfile: Dockerfile
    container_name: billing
    # volumes:
    #   - static_volume:/app/static
    env_file:
      - ./.env
    # environment:
    #   - POSTGRES_DB=notif_db
    #   - POSTGRES_HOST=notif_db
    # depends_on:
    #   - notif_db
    # command: bash -c "python script.py && gunicorn admin_notif.wsgi --bind 0.0.0.0:443"
    ports:
      - '443:443' 
    networks:
      - billing_nw
    restart: on-failure

  redis:
    image: redis:alpine
    container_name: redis
    env_file: 
      - ./.env
    volumes:
      - redis_data:/redis/data
    restart: always
    networks:
      - billing_nw

  billing_db:
    image: postgres:13-alpine
    container_name: billing_db
    env_file: 
      - ./.env
    volumes:
      - billing_db_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - billing_nw

volumes:
  redis_data:
  billing_db_data:

networks:
  billing_nw:
    driver: bridge