auth_create_url: str = 'http://flask_auth:5000/auth/api/v1/user_crud'
auth_get_id_url: str = 'http://flask_auth:5000/auth/api/v1/get_user_by_name'
auth_get_role_url: str = 'http://flask_auth:5000/auth/api/v1/user/roles'
create_url: str = 'https://billing:443/yookassa/api/v1/buy_subscription'
redis_url: str = 'redis://redis_bill:6379'
pg_bill_url: str = 'postgresql+asyncpg://app:123qwe@billing_db/billing_db'
