FROM python:3.10.9-slim

WORKDIR /billing
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir
# COPY ./ssl .
COPY . .
CMD ["python", "main_worker.py"]