"""init

Revision ID: 21ed09b0b970
Revises: 
Create Date: 2023-04-15 20:59:38.636958

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '21ed09b0b970'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('days', sa.Interval(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('description', sa.String(length=127), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('userstatus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('actual', sa.Boolean(), nullable=True),
    sa.Column('expires_status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('payment', sa.String(length=127), nullable=False),
    sa.Column('income', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('succeeded', 'canceled', 'pending', 'refund', name='statusenum'), nullable=False),
    sa.Column('tariff_id', sa.UUID(), nullable=True),
    sa.Column('userstatus_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['tariff_id'], ['tariff.id'], ),
    sa.ForeignKeyConstraint(['userstatus_id'], ['userstatus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('userstatus')
    op.drop_table('tariff')
    # ### end Alembic commands ###
