# Generated by Django 4.1.7 on 2023-04-14 12:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('days', models.DurationField(editable=False)),
                ('price', models.FloatField()),
                ('description', models.CharField(editable=False, max_length=127, verbose_name='description')),
            ],
            options={
                'db_table': 'public"."tariff',
            },
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'public"."userstatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentPG',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(editable=False)),
                ('payment', models.CharField(editable=False, max_length=127, verbose_name='payment')),
                ('income', models.FloatField(editable=False)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('canceled', 'Canceled'), ('pending', 'Pending'), ('refund', 'Refund')], editable=False, max_length=9)),
                ('tariff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.tariff')),
                ('userstatus_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.userstatus')),
            ],
            options={
                'db_table': 'public"."payment',
            },
        ),
    ]
